<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My Albums';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <button><a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
 </p></button>

 <table class="table" style="background-color:powderblue;" >
 <tr>
     <th>FristName</th>
     <th>LastName</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($album->title);?></td>
     <td><?php echo $this->escapeHtml($album->artist);?></td>
        <td>
            <a href="<?php echo $this->url('album',
                array('action'=>'edit', 'id' => $album->id));?>">Edit</a>   
             &nbsp; &nbsp;
         <a href="<?php echo $this->url('album',
             array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
